### PR TITLE
Journeys feedback

### PR DESCRIPTION
**Pull request by Bluesmile82**
Journeys feedback
    
- [X] Show journey API slides on the home page
- [X] Fix chapter step image with filter
- [X] Fix view button position on map
-  <del>[ ] Fix map not centering properly on revisit  </del> - I can't reproduce this 🤷 
- [x] Remove Private Banner on embed maps on the Journeys
- [x]  Next Journey button is not working correctly
- [x] Some maps not displaying

## Testing instructions

Create a new journey and check the home page 

Also, see if the chapter steps are displayed correctly on the journeys

See that the view button on a map step is always displayed properly even if its the last step

Go to an embed map step and check that we don't see the Private Banner inside the embed

Test the next buttons on the steps. They should guide you through the journeys

## Tracking

https://vizzuality.atlassian.net/browse/RA2-24?atlOrigin=eyJpIjoiMDNjN2NjZmYxNjI3NGUzMmE3YmU3NGZjNzc3MzUwMjUiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by Bluesmile82** [comment]
@clementprdhomme @davidsingal Could any of you review this PR?

**Review by clementprdhomme — COMMENTED** [review]
Hey Álvaro,

From the code point of view, I don't have any comment. I have found a few issues that we could address though:

- The links are not displayed correctly in the conclusion steps (see between “dolor” and “amet”)

The links use the default blue/purple colour which make them hardly visible on top of the brown background

- The chapter numbers are not correctly aligned in the chapter steps

The chapter numbers are stuck to the left of the screen instead of being position more towards the center

In my examples, I've always used two-digit chapter numbers but I don't think that's a concern.

- If the admin create an embedded map with a short URL, the application crashes (for example https://staging.resilienceatlas.org/share/ad684a048d482f4d361a)

Do you think we could fix this front-end wise? Should we put a restriction on the back-office?

**Comment by Bluesmile82** [comment]
> * https://staging.resilienceatlas.org/share/ad684a048d482f4d361a

About the numbers position. I followed the design: https://www.figma.com/file/ulN4NKgXHHDncKyIZBeYqV/Resilience-Atlas-%5BInternal%5D?node-id=0%3A4957&t=RWtPJbX8BcmXCvx1-1

I will take a look on the other two issues. Thanks

**Comment by Bluesmile82** [comment]
Ready again: 
- I added the background color to the background and background of the text container
- I made the map embed more resilient. It will display a 404 but it wont crash
- I Fixed the link style. These were also wrong in production
- I moved the hexToRGB function to the helpers file

**Review by clementprdhomme — APPROVED** [review]

**Review by davidsingal — APPROVED** [review]

**Pull request merged**
